### ISSUE TITLE
Recipes not using tags

### ISSUE THREAD

**Issue by RogueLogix** [ZeroNoRyouki/ExtremeReactors2-issues#1]
Recipes do not use tags for resources such as yellorium/uranium and graphite, despite ingots/dusts being tagged. To avoid incompatibility between our mods i will be tagging my ingots/dusts/recipes and using tags that mimmick what you have setup.

**Comment by ZeroNoRyouki** [comment]
Since this is a good thing for the players, I changed the recipes in 2.0.1

**Comment by RogueLogix** [comment]
i know you don't have it added yet, but, when you add your turbine and steam, make sure to tag it with `forge:fluids/steam` and have the turbine accept any `forge:fluids/steam` so the reactors/turbines (and other mod's steams) are cross compatible. _im sure you were gonna do this anyway, but it cant hurt too tell you anyway_

if there are/will be more recipe conflicts, feel free to open up an issue on my repo for it.

**Comment by ZeroNoRyouki** [comment]
My API uses only Tags

**Comment by pupnewfster** [comment]
Randomly looked at this, and hate to say it @RogueLogix but that is a stupid tag, steam should be tagged `forge:steam`. It already is a *fluid tag* (`ITag<Fluid>`), you don't need fluid in the name of the tag. That would be like all having the item tag for iron ore  be `forge:items/ores/iron` instead of just `forge:ores/iron`

**Comment by RogueLogix** [comment]
Typo on my part here, I do use the `forge:steam` fluid tag.
