### ISSUE TITLE
Auto on/off not working correctly

### ISSUE THREAD

**Issue by mellamokb** [ZeroNoRyouki/ExtremeReactors2-issues#7]
Hi :)

I'm using this mod now that it is included in TNP Limitless 3.  I used to use old Extreme Reactors in 1.12.  I'm using my standard setup to automate turning it on and off.

3 Redstone Ports.
- 1 port set to signal below 10%
- 1 port set to signal above 90%
- 1 port set to turn on/off on pulse.

They are all wired together with simple vanilla redstone.  When I am standing there watching, it seems to trigger correctly in both directions.  However it has happened 3 or 4 times now, if I'm in a separate area (like the nether), I come back to find the reactor either on full bore at 100%, or off at 0%.  The whole thing sits in a single chunk (it's only 5x5x1), and it is chunkloaded with FTB Utils.

I will keep trying to troubleshoot what is happening, but it seems something is buggy between this automation setup and chunkloading somewhere.

Thanks!!

**Comment by ZeroNoRyouki** [comment]
Thank you for letting me know. Could you please post a pic of your redstone setup somewhere so I could rebuild it and check this out?

**Comment by mellamokb** [comment]
Here is the layout of the redstone.  The leftmost port is above 90% trigger, second one is below 10% trigger, and the other port on the other side is the pulse trigger to turn the reactor on/off.

![2020-11-19_16 21 14](https://user-images.githubusercontent.com/3180641/99728427-6c3fbc80-2a87-11eb-8e65-23d8dcd603fc.png)

I think I may have figured it out some potential problem.  Apparently the redstone signal leaks out of the corner through the corner block, and sometimes triggers in weird ways.  For instance I captured this screenshot that doesn't make any sense to me.  Both lines are hot, even though both ports are off, and the port on the right is on, even though it should be a receiving only port.

![2020-11-19_16 41 37](https://user-images.githubusercontent.com/3180641/99728518-8da0a880-2a87-11eb-99ea-618a4b675493.png)

I am going to try moving the redstone line out one further so it doesn't pick up residual redstone around the side.  But is it new behavior that the port to receive an on/off signal can also output a redstone signal?

Also, when it's in this state, if I break and replace the redstone, it all goes dark again.  It's as though something is not properly propagating the block updates in certain conditions.  And this time I was standing here the whole time when it happened so it seems to have nothing to do with chunkloading either.

**Comment by mellamokb** [comment]
I was watching it again as it went below 10%, and this time the port lit up, but no redstone signal activated.  I had to break and replace the redstone dust directly adjacent and then it kicked on correctly.  So it does seem to be some issue with block update not triggering neighboring blocks correctly when the redstone port changes signal.

![2020-11-19_16 58 03](https://user-images.githubusercontent.com/3180641/99729172-875efc00-2a88-11eb-9025-10b4d2c60139.png)

**Comment by ZeroNoRyouki** [comment]
> But is it new behavior that the port to receive an on/off signal can also output a redstone signal?

Nop, the Redstone Port turn bright red when it is receiving a redstone signal OR is emitting one

**Comment by ZeroNoRyouki** [comment]
> So it does seem to be some issue with block update not triggering neighboring blocks correctly when the redstone port changes signal.

It does look like that indeed. I'll run some tests and see what's going on

**Comment by Gluton-Official** [comment]
I have noticed this too, an on/off mode redstone port does not de-power unless it is broken, and a battery level mode port does not turn off once the battery storage falls below the percentage after turning on once the battery level reaches/goes above the target precentage.

**Comment by mellamokb** [comment]
@Gluton-Official Ahh.. excellent point.  I do sort of remember that from the old BigReactors.  You needed to actually run the redstone one block above the port.  I changed my reactor to be wired one block above the output ports, but I still had to do it the same level for the input port, and now it seems to be working as expected.  IIRC in the old BigReactors it wouldn't emit a redstone signal at all one block below so you wouldn't make that mistake.

**Comment by papaworld** [comment]
Hi, I've had the same issues with using the "hardset" redstone signal of ON or OFF. Found that PULSE works much better. Here's a pix below.

![2020-11-24_09 14 26](https://user-images.githubusercontent.com/50890375/100113270-bf25c500-2e35-11eb-95b2-1b4746f20830.png)

Redstone Ports that are set to OUTPUT a signal from the reactor also activate the adjacent blocks... note how the Redstone wiring is attached to a Reactor Casing Block and also note there is NO connection to the Reactor from the TOGGLE LATCH (prevent backfeeding of signal).

Redstone Port on LEFT is LOW Energy Storage (Reactor ON). Restone Port on RIGHT is HIGH Energy Storage (Reactor OFF). The logic gates are vanilla MineCraft Repeater (4 ticks) and Comparator (subtractor mode). TOGGLE LATCH is from PowerCraft Gates Mod feeds the CENTER Redstone INPUT set to Turn the Reactor ON and OFF.

The 2 Yellow buttons are Momentary ON buttons from Redstone Gauges and Switches for 1st time setup and future manual control. Otherwise it will run totally automatic.

The pulsing and latching circuit is very similar to the ones I've used in 1.12.2 systems.

Hope this helps for a workaround.

**Comment by ZeroNoRyouki** [comment]
OK so, I should have fixed it:

T0, no energy in the buffer, port "below 10%" emitting signal:
![issue7 T0 start](https://user-images.githubusercontent.com/7107662/100220323-79412d80-2f17-11eb-9183-eef05ad08393.png)
![issue7 T0 start (no energy)](https://user-images.githubusercontent.com/7107662/100220330-7c3c1e00-2f17-11eb-8100-72f06e8bfd7b.png)

T1, energy buffer filled more than 10%, no redstone signals:
![issue7 T1 no more below 10%](https://user-images.githubusercontent.com/7107662/100220401-9bd34680-2f17-11eb-9d12-8ff093d611a4.png)
![issue7 T1 no more below 10% (energy)](https://user-images.githubusercontent.com/7107662/100220409-9f66cd80-2f17-11eb-87e6-6af41371ec7a.png)

T2. energy buffer filled more than 90%, relevant port emitting signal, reactor is off:
![issue7 T2 above 90%](https://user-images.githubusercontent.com/7107662/100220520-c6bd9a80-2f17-11eb-87c3-5f6ff40ebc0e.png)
![issue7 T2 above 90% (energy)](https://user-images.githubusercontent.com/7107662/100220527-c8875e00-2f17-11eb-9520-c22d041fe8f5.png)

Now the Redstone Port emit power from it's own block as it probably did not make sense otherwise even in 1.10+

![2020-11-25_12 10 08](https://user-images.githubusercontent.com/7107662/100220807-22882380-2f18-11eb-9e28-4b707f195abe.png)
![2020-11-25_12 10 30](https://user-images.githubusercontent.com/7107662/100220812-2320ba00-2f18-11eb-866c-393676d41735.png)

I should release and update version later today

**Comment by ZeroNoRyouki** [comment]
2.0.9 is out

**Comment by mellamokb** [comment]
I can confirm on 2.0.10 now the redstone works correctly on the same level as the redstone ports.  Thanks!!

**Comment by ZeroNoRyouki** [comment]
Thank you, have fun!
